In [1]:
from sklearn import datasets, linear_model
from sklearn.linear_model import Lasso
import numpy as np
from sklearn.model_selection import GridSearchCV

In [2]:
dataset = datasets.load_diabetes()

In [3]:
X = dataset.data
Y = dataset.target 

In [4]:
X.shape

(442, 10)

In [5]:
Y.shape

(442,)

In [6]:
X[:5]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567042, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286131, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665608,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02268774, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187239,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03198764, -0.04664087]])

In [7]:
Y[:10]

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310.])

In [8]:
feature_names=['age', 'sex', 'bmi', 'bp','s1', 's2', 's3', 's4', 's5', 's6']

In [9]:
X_train = dataset.data[:310]
Y_train = dataset.data[:310]

X_test = dataset.data[310:]
Y_test = dataset.data[310:]

In [10]:
lasso = Lasso(random_state=0)
alphas = np.logspace(-4,-0.5,30)

In [11]:
estimator = GridSearchCV(lasso,dict(alpha=alphas))


In [12]:
estimator.fit(X_train,Y_train)

GridSearchCV(estimator=Lasso(random_state=0),
             param_grid={'alpha': array([1.00000000e-04, 1.32035178e-04, 1.74332882e-04, 2.30180731e-04,
       3.03919538e-04, 4.01280703e-04, 5.29831691e-04, 6.99564216e-04,
       9.23670857e-04, 1.21957046e-03, 1.61026203e-03, 2.12611233e-03,
       2.80721620e-03, 3.70651291e-03, 4.89390092e-03, 6.46167079e-03,
       8.53167852e-03, 1.12648169e-02, 1.48735211e-02, 1.96382800e-02,
       2.59294380e-02, 3.42359796e-02, 4.52035366e-02, 5.96845700e-02,
       7.88046282e-02, 1.04049831e-01, 1.37382380e-01, 1.81393069e-01,
       2.39502662e-01, 3.16227766e-01])})

In [17]:
from sklearn.preprocessing import normalize
GridSearchCV(cv=None,error_score='raise',
             estimator=Lasso(alpha=1.0,copy_X=True,fit_intercept=True,max_iter=1000,positive=False,precompute=False,random_state=0,selection='cyclic',tol=0.0001,warm_start=False),
             n_jobs=1,
             param_grid={'alpha': np.array([1.00000e-04, 1.32035e-04, 1.74333e-04, 2.30181e-04,3.03920e-04, ..., 2.39503e-01, 3.16228e-01])},
             pre_dispatch='2*n_jobs',refit=True,return_train_score=True,scoring=None,verbose=0
             )

GridSearchCV(error_score='raise', estimator=Lasso(random_state=0), n_jobs=1,
             param_grid={'alpha': array([0.0001, 0.000132035, 0.000174333, 0.000230181, 0.00030392,
       Ellipsis, 0.239503, 0.316228], dtype=object)},
             return_train_score=True)

In [18]:
estimator.best_score_

0.9979150380794971

In [19]:
estimator.best_estimator_

Lasso(alpha=0.0001, random_state=0)

In [20]:
estimator.predict(X_test)

array([[-0.00530817, -0.04267064,  0.06179948, ...,  0.0005778 ,
        -0.0173604 ,  0.03055607],
       [ 0.09204424, -0.04267064,  0.03816798, ...,  0.03441452,
         0.01183381,  0.0226356 ],
       [-0.07136873, -0.04267064, -0.02245196, ..., -0.03784098,
        -0.03673064, -0.02884745],
       ...,
       [ 0.03989116,  0.04843726, -0.01525976, ..., -0.01070111,
        -0.0447495 ,  0.01471513],
       [-0.04355376, -0.04267064,  0.03714052, ...,  0.02525041,
         0.04227772, -0.02488721],
       [-0.04355376, -0.04267064, -0.06971496, ..., -0.03784098,
        -0.00413448,  0.00283443]])